user:
    name: Melodee Helene Beals
    affiliation: Loughborough University
    orcid: 
    gravatarhash: 82b4d22865fcd47198ac2bd283b3f08e
        
        
        
        
articles:
    1:
        title: The Role of the Sydney Gazette in the Creation of Australia in the Scottish Public Sphere
        doi: 10.6084/M9.FIGSHARE.944593
        summary: Building upon my postgraduate research, I turned to a deeper analysis of Scottish journalism, namely the representations of colonial Australia in the early years of the nineteenth century. This article represents my first work on Scissors-and-Paste journalism.
        image: https://c2.staticflickr.com/8/7503/15795863409_f8a8bd3bd9_z.jpg
